class SubordinateCreateResponse {
  bool? status;
  String? message;
  int? userId;
  String? email;
  String? autoGeneratedPassword;
  bool? autoApproved;
  int? assignedProperties;

  SubordinateCreateResponse({
    this.status,
    this.message,
    this.userId,
    this.email,
    this.autoGeneratedPassword,
    this.autoApproved,
    this.assignedProperties,
  });

  SubordinateCreateResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    userId = json['user_id'];
    email = json['email'];
    autoGeneratedPassword = json['auto_generated_password'];
    autoApproved = json['auto_approved'];
    assignedProperties = json['assigned_properties'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['user_id'] = userId;
    data['email'] = email;
    data['auto_generated_password'] = autoGeneratedPassword;
    data['auto_approved'] = autoApproved;
    data['assigned_properties'] = assignedProperties;
    return data;
  }
}
